name: Build Wheels

on: [push, pull_request]

jobs:
  wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15, macos-13, windows-latest]  # Use specific versions for clarity
        arch: [x86_64, arm64]
        exclude:
          - os: ubuntu-24.04-arm  # No need to specify arch, it's already implicit
            arch: x86_64  # Exclude x86_64 on ARM
          - os: macos-15   # Exclude macOS 14 (Sonoma)
            arch: x86_64   # Exclude x86_64 explicitly
          - os: macos-13  # Exclude macOS 13 (Ventura) - arm64
            arch: arm64   # Exclude arm64 on macOS 13
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.11'
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.22.0
    - name: Build wheel
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CIBW_SKIP: "cp*-manylinux_i686 cp*-musllinux* cp*-win32"
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.pybuilds }}
        path: dist/

  release:
    permissions:
      contents: write  # for actions/create-release
    name: Create GitHub Release
    needs: [wheels]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Tag Version
        id: set_tag
        run: |
          export V=$(python -c "print(next(iter(eval(L.split('=')[-1]) for L in open('pyproject.toml') if 'version =' in L)))")
          echo "tag=${V}" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v4
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ env.tag }}
          artifacts: "wheels/*.whl"
  pypi-publish:
    name: Release to PyPI
    needs: [wheels]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Wheels
        uses: actions/download-artifact@v4
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels
